/* Nontrivial zeros of ζ on the critical line: imaginary parts t_k.
   This list is regenerated by scripts/genzeros.mjs (root-finding on the
   Dirichlet-eta evaluation of ζ(1/2 + it)); the first 29 values match the
   published zeros below t = 100 to the precision shown. */

export const ZEROS = [14.1347, 21.022, 25.0109, 30.4249, 32.9351, 37.5862, 40.9187, 43.3271,
  48.0052, 49.7738, 52.9703, 56.4462, 59.347, 60.8318, 65.1125, 67.0798, 69.5464,
  72.0672, 75.7047, 77.1448, 79.3374, 82.9104, 84.7355, 87.4253, 88.8091, 92.4919,
  94.6513, 95.8706, 98.8312];
